djangoflights/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('search/', views.search, name='search'),
  path('airports/', views.airports_index, name='airports_index'),
  path('airports/<int:airport_id>/', views.airports_detail, name='airports_detail'),
  path('airports/<int:airport_id>/assoc_airport/<int:profile_id>/', views.assoc_airport, name='assoc_airport'),
  path('airports/<int:airport_id>/remove_assoc/<int:profile_id>/', views.remove_assoc_airport, name='remove_assoc_airport'),
  path('tickets/', views.TicketList.as_view(), name='tickets_index'),
  path('tickets/create/', views.TicketCreate.as_view(), name='tickets_create'),
  path('tickets/<int:pk>/', views.TicketDetail.as_view(), name='tickets_detail'),
  path('tickets/<int:pk>/delete/', views.TicketDelete.as_view(), name='tickets_delete'),
  path('tickets/<int:pk>/update/', views.TicketUpdate.as_view(), name='tickets_update'),
  path('accounts/signup/', views.signup, name='signup')
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

CLASSES = (
  ('E', 'Economy'),
  ('B', 'Business'),
  ('F', 'First Class')
)

class Airport(models.Model):
  name = models.CharField('Airport Name', max_length=100, blank=True)
  iata = models.CharField('3-digit Airport Code', max_length=3, blank=True, unique=True)
  iso = models.CharField('Country Code', max_length=2)
  lat = models.DecimalField(decimal_places=6, max_digits=12)
  lon = models.DecimalField(decimal_places=6, max_digits=12)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("airports_detail", kwargs={"airport_id": self.id})

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  airport = models.ManyToManyField(Airport, blank=True)

class Ticket(models.Model):
  price = models.IntegerField()
  seat = models.CharField(
    max_length=3,
    validators=[
      RegexValidator('^0[1-4][A-D]|0[5-9][A-G]|1[0-5][A-G]|1[6-9][A-J]|2[0-9][A-J]|3[0-4][A-J]$',
        message='Please follow instructions on picking a seat number.',
        code='invalid_seat'
      )
    ]
  )
  seat_class = models.CharField(
    max_length=1,
    choices=CLASSES,
    default=CLASSES[0][0],
  )
  date = models.DateTimeField()
  origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='origin_airport')
  destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='destination_airport')
  profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

  def __str__(self):
    return f'Ticket #{self.id}'

  def get_absolute_url(self):
    return reverse("tickets_detail", kwargs={"pk": self.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Airport

class SearchAirportForm(ModelForm):
  class Meta:
    model = Airport
    fields = ['name', 'iata']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.conf import settings
from .forms import SearchAirportForm
from .models import Airport, Profile, Ticket
from decimal import Decimal
from math import radians, cos, sin, asin, sqrt
import re
import requests
from datetime import datetime

# https://en.wikipedia.org/wiki/Haversine_formula
def calculate_distance(origin_lat, origin_lon, dest_lat, dest_lon):
  radius = 3959.87433
  lat1 = radians(origin_lat)
  lat2 = radians(dest_lat)
  d_lat = radians(dest_lat - origin_lat)
  d_lon = radians(dest_lon - origin_lon)
  angle = asin(sqrt(sin(d_lat/2)**2 + cos(lat1)*cos(lat2)*sin(d_lon/2)**2))
  return 2*radius*angle

def calculate_price(seat_class, origin_lat, origin_lon, dest_lat, dest_lon):
  base = 48
  modifier = 1
  if seat_class == 'B':
    modifier = 1.5
  if seat_class == 'F':
    modifier = 3
  distance = calculate_distance(origin_lat, origin_lon, dest_lat, dest_lon)
  return base + int(modifier * distance/12)

def calculate_travel_time(miles):
  minutes = round((miles/475) * 60)
  hours = int(minutes/60)
  if hours == 0:
    return f'{minutes} minutes'
  minutes = minutes % 60
  if minutes == 0:
    return f'{hours} hours'
  return f'{hours} hours {minutes} minutes'

class Home(LoginView):
  template_name = 'home.html'

class TicketList(LoginRequiredMixin, ListView):
  model = Ticket

  def get_queryset(self):
    return Ticket.objects.filter(profile_id=self.request.user.id)

class TicketDetail(LoginRequiredMixin, DetailView):
  model = Ticket

  def get_context_data(self, **kwargs):
    context = super(TicketDetail, self).get_context_data(**kwargs)
    origin = context['object'].origin
    dest = context['object'].destination
    context['distance'] = round(calculate_distance(origin.lat, origin.lon, dest.lat, dest.lon),2)
    context['travel_time'] = calculate_travel_time(context['distance'])
    return context

class TicketCreate(LoginRequiredMixin, CreateView):
  model = Ticket
  fields = ['seat', 'date', 'origin', 'destination']

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    airports = Profile.objects.get(id=self.request.user.id).airport.all()
    context['form'].fields['origin'].queryset = airports
    context['form'].fields['destination'].queryset = airports
    return context

  def form_valid(self, form):
    if form.instance.origin == form.instance.destination:
      return super().form_invalid(form)
    form.instance.seat_class = 'E'
    if re.search(r'0[1-4][A-D]', form.instance.seat):
      form.instance.seat_class = 'F'
    if re.search(r'0[5-9][A-G]|1[0-5][A-G]', form.instance.seat):
      form.instance.seat_class = 'B'
    form.instance.price = calculate_price(form.instance.seat_class, form.instance.origin.lat, form.instance.origin.lon, form.instance.destination.lat, form.instance.destination.lon)
    form.instance.profile = Profile.objects.get(id=self.request.user.id)
    return super().form_valid(form)

class TicketDelete(LoginRequiredMixin, DeleteView):
  model = Ticket
  success_url = '/tickets/'

class TicketUpdate(LoginRequiredMixin, UpdateView):
  model = Ticket
  fields = ['seat']

  def form_valid(self, form):
    form.instance.seat_class = 'E'
    if re.search(r'0[1-4][A-D]', form.instance.seat):
      form.instance.seat_class = 'F'
    if re.search(r'0[5-9][A-G]|1[0-5][A-G]', form.instance.seat):
      form.instance.seat_class = 'B'
    form.instance.price = calculate_price(form.instance.seat_class, form.instance.origin.lat, form.instance.origin.lon, form.instance.destination.lat, form.instance.destination.lon)
    form.instance.profile = Profile.objects.get(id=self.request.user.id)
    return super().form_valid(form)

def about(request):
  return render(request, 'about.html')

def search(request):
  results = []
  if request.GET.get('iata') or request.GET.get('name'):
    iata = request.GET.get('iata')
    name = request.GET.get('name')
    response = requests.get('https://raw.githubusercontent.com/jbrooksuk/JSON-Airports/master/airports.json')
    for obj in response.json():
      if 'name' in obj and 'iata' in obj and 'iso' in obj and 'lat' in obj and 'lon' in obj and obj['name'] != None and obj['iata'] != None and obj['iso'] != None and obj['lat'] != None and obj['lon'] != None:
        if iata and name:
          if name in obj['name'].lower() and iata.upper() in obj['iata'] and len(results) < 30:
            results.append(obj)
        elif name and name in obj['name'].lower() and len(results) < 30:
          results.append(obj)
        elif iata and iata.upper() in obj['iata'] and len(results) < 30:
          results.append(obj)
    for result in results:
      if (len(Airport.objects.filter(iata=result['iata'])) == 0) and result['name'] != None and result['iata'] != None and result['iso'] != None and result['lat'] != None and result['lon'] != None:
        result_data = Airport(
          name = result['name'],
          iata = result['iata'],
          iso = result['iso'],
          lat = Decimal(result['lat']),
          lon = Decimal(result['lon'])
        )
        result_data.save()
  send_results = Airport.objects.filter(iata__in=[result['iata'] for result in results])
  return render(request, 'search.html', {
    'form': SearchAirportForm(),
    'results': send_results
  })

@login_required
def airports_index(request):
  airports = Profile.objects.get(id=request.user.id).airport.all()
  return render(request, 'main_app/airport_list.html', {
    'airports': airports
  })

def k_to_f(k):
  return int((k - 273.15)*(9/5)+32)

def get_index(idx):
  level = 'Good'
  if idx == 2:
    level = 'Moderate'
  elif idx == 3:
    level = 'Poor'
  elif idx == 4:
    level = 'Unhealthy'
  elif idx == 5:
    level = 'Very Unhealthy'
  return level

def airports_detail(request, airport_id):
  airport = Airport.objects.get(id=airport_id)
  airport_details = requests.get(f'https://api.openweathermap.org/data/2.5/weather?lat={airport.lat}&lon={airport.lon}&appid={settings.WEATHER_API}').json()
  air_pollution = requests.get(f'http://api.openweathermap.org/data/2.5/air_pollution?lat={airport.lat}&lon={airport.lon}&appid={settings.WEATHER_API}').json()
  img_url = f"http://openweathermap.org/img/wn/{airport_details['weather'][0]['icon']}@2x.png"
  airport_details['visibility'] = round(airport_details['visibility']/1000, 3)
  temps = {
    'temp': k_to_f(airport_details['main']['temp']),
    'feels_like': k_to_f(airport_details['main']['feels_like']),
    'temp_min': k_to_f(airport_details['main']['temp_min']),
    'temp_max': k_to_f(airport_details['main']['temp_max'])
  }
  sunrise = datetime.fromtimestamp(airport_details['sys']['sunrise'] + airport_details['timezone']).strftime('%I:%M %p')
  sunset = datetime.fromtimestamp(airport_details['sys']['sunset'] + airport_details['timezone']).strftime('%I:%M %p')
  air_pollution_index = air_pollution['list'][0]['main']['aqi']
  air_pollution_level = get_index(air_pollution_index)
  if (request.user.id is not None):
    profile = Profile.objects.get(id=request.user.id)
    return render(request, 'main_app/airport_detail.html', {
      'profile': profile,
      'profile_airport': profile.airport.all(),
      'airport': airport,
      'airport_details': airport_details,
      'air_pollution': air_pollution,
      'img_url': img_url,
      'temps': temps,
      'sunrise': sunrise,
      'sunset': sunset,
      'air_pollution_index': air_pollution_index,
      'air_pollution_level': air_pollution_level
    })
  else:
    return render(request, 'main_app/airport_detail.html', {
      'airport': airport,
      'airport_details': airport_details,
      'air_pollution': air_pollution,
      'img_url': img_url,
      'temps': temps,
      'sunrise': sunrise,
      'sunset': sunset,
      'air_pollution_index': air_pollution_index,
      'air_pollution_level': air_pollution_level
    })

@login_required
def assoc_airport(request, airport_id, profile_id):
  Profile.objects.get(id=profile_id).airport.add(airport_id)
  return redirect('airports_detail', airport_id=airport_id)

@login_required
def remove_assoc_airport(request, airport_id, profile_id):
  airport_to_be_removed = Airport.objects.get(id=airport_id)
  Profile.objects.get(id=profile_id).airport.remove(airport_to_be_removed)
  return redirect('airports_detail', airport_id=airport_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      profile = Profile(user=user)
      profile.save()
      # This is how we log a user in
      login(request, user)
      return redirect('airports_index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/main_app/airport_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/airport-detail.css' %}"
/>
{% endblock head %}
{% block content %}
<div class='total-airport'>
  <div class='airport-name'>
    <h1 style="font-size:8em;">{{airport.iata}}</h1>
    <h1>{{airport}}</h1>
  </div>
  <div class='lower-half-airport'>
    <div class='weather'>
      <div class='upper-weather'>
        <h2>Location: {{airport_details.name}}, {{airport_details.sys.country}}</h2>
        <img src={{img_url}} alt='Weather Icon'/>
        <h3>{{airport_details.weather.0.main}}</h3>
      </div>
      <div class='lower-weather'>
        <div>
          <h5>Temperature: {{temps.temp}}°F</h5>
          <h5>Feels Like: {{temps.feels_like}}°F</h5>
          <h5>Sunrise: {{sunrise}}</h5>
          <h5>Sunset: {{sunset}}</h5>
        </div>
        <div>
          Day High: {{temps.temp_max}}°F<br />
          Day Low: {{temps.temp_min}}°F<br />
          Air Pressure: {{airport_details.main.pressure}}hPa<br />
          Humidity: {{airport_details.main.humidity}}%<br />
          Visibility: {{airport_details.visibility}}km
        </div>
      </div>
    </div>
    <div class='pollution'
      {% if air_pollution_index == 1 %}
        style='background-color: rgba(144, 238, 144, 0.8);'
      {% elif air_pollution_index == 2 %}
        style='background-color: rgba(255, 225, 0, 0.8);'
      {% elif air_pollution_index == 3 %}
        style='background-color: rgba(255, 165, 0, 0.8);'
      {% elif air_pollution_index == 4 %}
        style='background-color: rgba(255, 0, 0, 0.8); color: white;'
      {% else %}
        style='background-color: rgba(139, 0, 139, 0.8); color: white;'
      {% endif %}
    >
      <div class='pollution-left'>
        <h2>AQI Rating</h2>
        <img
          {% if air_pollution_index == 1 %}
            src={% static 'images/ap1.svg' %}
          {% elif air_pollution_index == 2 %}
            src={% static 'images/ap2.svg' %}
          {% elif air_pollution_index == 3 %}
            src={% static 'images/ap3.svg' %}
          {% elif air_pollution_index == 4 %}
            src={% static 'images/ap4.svg' %}
          {% else %}
            src={% static 'images/ap5.svg' %}
          {% endif %}
          width='200px'
          alt='air pollution level'
        ><br />
        <h3>{{air_pollution_level}}</h3>
      </div>
      <div>
        <h5>Air Pollution Indexes (μg/m<sup>3</sup>)</h5><br />
        Carbon monoxide (CO): {{air_pollution.list.0.components.co}}<br />
        Nitrogen monoxide (NO): {{air_pollution.list.0.components.no}}<br />
        Nitrogen dioxide (NO<sub>2</sub>): {{air_pollution.list.0.components.no2}}<br />
        Ozone (O<sub>3</sub>): {{air_pollution.list.0.components.o3}}<br />
        Sulphur dioxide (SO<sub>2</sub>): {{air_pollution.list.0.components.so2}}<br />
        Fine particles (PM<sub>2.5</sub>): {{air_pollution.list.0.components.pm2_5}}<br />
        Coarse particles (PM<sub>10</sub>): {{air_pollution.list.0.components.pm10}}<br />
        Ammonia (NH<sub>3</sub>): {{air_pollution.list.0.components.nh3}}
      </div>
    </div>
  </div>
  <div class='airport-button'>
    {% if user.is_authenticated %}
      {% if airport in profile_airport %}
        <form action={% url 'remove_assoc_airport' airport.id profile.id %} method='post'>
          {% csrf_token %}
          <button type='submit' class='btn btn-danger'>Remove from your airport list</button>
        </form>
      {% else %}
        <form action={% url 'assoc_airport' airport.id profile.id %} method='post'>
          {% csrf_token %}
          <button type='submit' class='btn btn-primary'>Add to your airport list</button>
        </form>
      {% endif %}
    {% endif %}
  </div>
</div>
{% endblock content %}

main_app/templates/main_app/airport_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/list.css' %}"
/>
{% endblock head %}
{% block content %}
<h1><span>Your Airports</span></h1>
<br />
{% if airports %}
<table class='table'>
  <thead>
    <tr>
      <th scope='col'>Airport Name</th>
      <th scope='col'>Airport Code</th>
      <th scope='col'>Country Code</th>
      <th scope='col'></th>
    </tr>
  </thead>
  <tbody>
    {% for airport in airports %}
      <tr>
        <th scope='row'>{{airport.name}}</th>
        <td>{{airport.iata}}</td>
        <td>{{airport.iso}}</td>
        <td><a href={% url 'airports_detail' airport.id %} class='btn btn-info btn-sm' role='button'>Details</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<div class='no-object-info'>
  <div>
    <p>You have no airports saved on your profile! Please go <a href={% url 'search' %} class='django-link'>here</a> to search and add airports to your airport list!</p>
    <p><b>Note that you need to add at least 2 different airports to purchase a ticket.</b></p>
  </div>
</div>
{% endif %}
{% endblock content %}

main_app/templates/main_app/ticket_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/ticket-bg-delete.css' %}"
/>
{% endblock head %}
{% block content %}
<div class='outer-div'>
  <div class='inner-div-about'>
    <h1>Get Refund for {{ticket}}?</h1>
    <form action="" method="POST">
      {% csrf_token %}
      <div class='signup-button'>
        <a href={% url 'tickets_detail' ticket.id %} class='btn btn-warning' role='button'>
          Cancel
        </a>
        <button type="submit" class='btn btn-danger'>Yes - Get refund!</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/ticket_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script defer src="{% static 'js/ticket-form.js' %}"></script>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/ticket-detail.css' %}"
/>
{% endblock head %}
{% block content %}
<div class='ticket-outer-div'>
  <div class='ticket-inner-div
    {% if ticket.get_seat_class_display == "First Class" %}
      first-class-primary
    {% elif ticket.get_seat_class_display == "Business" %}
      business-primary
    {% endif %}
  '>
    <h1 id='upper-h1'>{{ticket}}</h1>
    <div class='ticket-inner-div-1'>
      <div>
        <h1>{{ticket.origin.iata}}</h1>
        {{ticket.origin.name}}
      </div>
      <div>
        <img
          src={% static 'images/airplane.png' %}
          width='210px;'
          alt='airplane'
        />
      </div>
      <div>
        <h1>{{ticket.destination.iata}}</h1>
        {{ticket.destination.name}}
      </div>
    </div>
    {% now "Y-m-d" as todays_date %}
    <h1
      {% if not todays_date < ticket.date|date:"Y-m-d" %}
        style='color: crimson; font-size: 2em;'
    >Departed
      {% else %}
        style='font-size: 2em;'
    >Departs    
      {% endif %}
    {{ticket.date}}</h1>
    <div class='ticket-inner-div-2'>
      <div>
        <h3>Distance: <b>{{distance}}mi</b></h3>
      </div>
      <div>
        <h3>Est. travel time: <b>{{travel_time}}</b></h3>
      </div>
    </div>
    <div class='ticket-inner-div-3'>
      <div>
        <h3>Class: <b>{{ticket.get_seat_class_display}}</b></h3>
      </div>
      <div>
        <h2>Seat: <b>{{ticket.seat}}</b></h2>
      </div>
      <div>
        <h3>Price: <b>${{ticket.price}}</b></h3>
      </div>
    </div>
  </div>
  <div class='ticket-detail-buttons'>
    <a href={% url 'tickets_index' %} class='btn btn-dark btn-lg' role='button'>Back</a>
    <a href={% url 'tickets_update' ticket.id %} class='btn btn-primary btn-lg' role='button'>Change Seat</a>
    <a href={% url 'tickets_delete' ticket.id %} class='btn btn-danger btn-lg' role='button'>Get Refund</a>
  </div>
</div>
{% endblock content %}

main_app/templates/main_app/ticket_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script defer src="{% static 'js/ticket-form.js' %}"></script>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/ticket-form.css' %}"
/>
{% endblock head %}
{% block content %}
<div class='ticket-form-outer'>
  <div class='ticket-form-left'>
    {% if object %}
      <h1>Change Seat</h1>
    {% else %}
      <h1>New Ticket</h1>
    {% endif %}
    <form action='' method="post">
      {% csrf_token %}
      <table>
        {{form.as_table}}
      </table>
      <div class='ticket-form-left-button'>
        <button type="submit" class='btn btn-success'>Submit</button>
        {% if object %}
          <a href={% url 'tickets_detail' ticket.id %} class='btn btn-warning' role='button'>
            Cancel
          </a>
        {% endif %}
      </div>
    </form>
  </div>
  <div class='ticket-form-right'>
    <h3>Seat Number Instructions</h3>
    01-04, A-D: First class<br />
    05-15, A-G: Business <br />
    16-34, A-J: Economy<br />
    <b>Seats numbered less than 10 must have a 0 in front.</b><br />
    <b>Seat numbers are case sensitive.</b><br />
    Examples of valid seat numbers: 03B, 05C, 13F, 20H, 31A<br />
    <h5 style='color: crimson;'><b>Your seat class and distance from origin to destination determines your ticket price.</b></h3>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/ticket_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/ticket-bg.css' %}"
/>
{% endblock head %}
{% block content %}
<h1><span>Your Tickets</span></h1>
<a href={% url 'tickets_create' %} class='btn btn-primary' role='button'>New Ticket</a>
<br />
<br />
<table class='table'>
  <thead>
    <tr>
      <th scope='col'>Ticket #</th>
      <th scope='col'>Origin</th>
      <th scope='col'>Destination</th>
      <th scope='col'>Departure Date</th>
      <th scope='col'>Seat</th>
      <th scope='col'>Class</th>
      <th scope='col'></th>
    </tr>
  </thead>
  <tbody>
    {% now "Y-m-d" as todays_date %}
    {% for ticket in ticket_list %}
      <tr
        {% if not todays_date < ticket.date|date:"Y-m-d" %}
          class='bg-danger'
        {% endif %}
      >
        <th scope='row'>{{ticket.id}}</th>
        <td>{{ticket.origin.iata}}</td>
        <td>{{ticket.destination.iata}}</td>
        <td>{{ticket.date}}</td>
        <td>{{ticket.seat}}</td>
        <td>{{ticket.get_seat_class_display}}</td>
        <td><a href={% url 'tickets_detail' ticket.id %} class='btn btn-info btn-sm' role='button'>Details</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}